# The compose file to build and run the necessary containers
# This builds two containers: One for a node.js server and one for a
#   nginx website that can connect to the node.js servers using websockets.
# Navigate to this file and use this command to run the containers:
#   docker-compose up -d --build --force-recreate
# Use this command to stop them:
#   docker-compose down

services:
  #The website itself
  website:
    image: nginx:latest
    container_name: website
    volumes: 
      - "./src/website/code/index.html:/usr/share/nginx/html/index.html:ro"
      - "./src/common/:/usr/share/nginx/html/common/:ro"
      - "./src/website/code/scripts/:/usr/share/nginx/html/scripts/:ro"
      - "./src/website/code/styles/:/usr/share/nginx/html/styles/:ro"
      - "./src/website/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 80:80
    restart: always
  #The Node.JS server connecting the website to the database
  server:
    build:
      context: /src/nodeserver
    container_name: server
    volumes:
      - "./src/nodeserver/package.json:/app/package.json:ro"
      - "./src/nodeserver/code:/app/code:ro"
      - "./src/common/:/common/:ro"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      db:
        condition: service_healthy
  #The database that stores everything
  # Use this command to log in once inside the container:
  #   mysql --user=root --password
  # Once properly set up, use the information in docs/DatabaseDesign.md
  #   initialize the database
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testytests
      MYSQL_DATABASE: ToDoBoardData
    ports:
      - "3306:3306"
    volumes:
      # Make MySql write to the computer
      - "./src/mysqldatabase/data:/var/lib/mysql"
    #Check to make sure the database is accepting connections every so often
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
      start_interval: 5s