# The compose file to build and run the necessary containers
# This builds two containers: One for a node.js server and one for a
#   nginx website that can send an HTTP request to the server.
# Navigate to this file and use this command to run the containers:
#   docker-compose up -d --build --force-restart
# Use this command to stop them:
#   docker-compose down

services:
  website:
    image: nginx:latest
    container_name: website
    volumes: 
      - "./testsite/code:/usr/share/nginx/html"
      - "./testsite/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80
    restart: always
  server:
    build:
      context: /testserver
    container_name: server
    #volumes:
      #- "./testserver/package.json:package.json"
      #- "./testserver/code:/app"
    ports:
      - "3000:3000"